Increment thirteen
r4start/go-url-shortener pull request #14
Opened 2022-04-24 09:07 UTC by r4start

2022-04-24 16:04 UTC, lugingf requested changes
В общем все хорошо и мне нравится. Небольшие замечания только по структуре. Давай чуть приберем

2022-04-24 16:04 UTC, lugingf commented on cmd/shortener/main.go
> +	} else {
Как думаешь, может стоить эти все переборы if/else спрятать из main куда-нибудь в пакет Storage, чтобы аккуратней смотрелось? Задно через `return st, nil` можно будет и else поубирать

2022-04-24 16:04 UTC, lugingf commented on cmd/shortener/main.go
> +		panic(err)
а давай все таки без паник? :) Определим логгер в самом начале и тогда через Fatal() будем завершать программу

2022-04-24 16:04 UTC, lugingf commented on internal/app/shortener_test.go
> +	h, err := NewURLShortener(nil, "", storage.NewInMemoryStorage(), logger)
Несколько раз в тестах это копипастится. Давай вынесем может?

2022-04-24 16:04 UTC, lugingf commented on internal/storage/dbstorage.go
> +		} else if affected != 0 {
тут else if не нужен, там же return

2022-04-24 16:04 UTC, lugingf commented on internal/storage/dbstorage.go
> +	} else {
и тут else не нужен :)

2022-04-24 16:04 UTC, lugingf commented on internal/storage/dbstorage.go
> +		} else if count, err := stmtResult.RowsAffected(); err != nil {
"else не нужны" (c) :D

2022-04-24 16:04 UTC, lugingf commented on internal/storage/storage.go
> +	Add(ctx context.Context, userID uint64, url string) (uint64, bool, error)
Я в прошлый раз проглядел, или спрашивал? А зачем мы exists отдаем?

2022-04-25 16:04 UTC, r4start commented on internal/storage/storage.go
> +	Add(ctx context.Context, userID uint64, url string) (uint64, bool, error)
Не спрашивал. Это было сделано для файлового стораджа, чтобы дубликаты не плодить.
Он под капотом ипользует inmemory хранилище и если ключ новый, то дозаписывает его в файл.
Можно в принципе убрать exists из внешнего интерфейса.

2022-04-26 17:22 UTC, lugingf commented on internal/storage/storage.go
> +	Add(ctx context.Context, userID uint64, url string) (uint64, bool, error)
Мне кажется, что если аргумент специфичен только для одной конкретной имплементации, то не стоит его объявлять глобально в интерфейсе

2022-05-01 11:10 UTC, r4start commented on internal/storage/dbstorage.go
> +		} else if affected != 0 {
В данном случае `else` нужен, т.к. тогда `affected` будет недоступен.
Перепишу в plain if-ах. Вижу что запутывает восприятие.

2022-05-01 11:23 UTC, r4start commented on internal/storage/storage.go
> +	Add(ctx context.Context, userID uint64, url string) (uint64, bool, error)
Так, а сейчас это необходимо для 13-го инкремента. Через этот параметр принимается решение отдавать 409 код или нет.

2022-05-01 11:31 UTC, r4start commented on cmd/shortener/main.go
> +	} else {
В пакет storage точно это добавлять не хочется. Не должен он знать про config приложения.
Пока вынес в функцию отдельную, чтобы не засорять код.
Можно как альтернативу рассмотреть прямо в cmd/shortener создать файл с этой функцией.

2022-05-02 15:33 UTC, lugingf approved these changes
Спасибо за ответы в коммкентариях!
Принято

2022-05-03 08:04 UTC, merged