Added delete urls basic implementation.
r4start/go-url-shortener pull request #15
Opened 2022-05-03 09:17 UTC by r4start

2022-05-13 13:03 UTC, lugingf requested changes
Оставил комментарии

2022-05-13 13:03 UTC, lugingf commented on internal/app/shortener.go
> +	for i := 0; i < strIDsLength; i += batchSize {
Вообще решение нормас, но в задаче немного другое требовалось.

2022-05-13 13:03 UTC, lugingf commented on internal/app/shortener.go
> +	if err := g.Wait(); err != nil {
Мы же тут все равно ждем пока все удалится. Идея была в том, чтобы оставить удаляться, а юзеру ответить что "да, все будет". А так мы ждем и блокируем систему, пока не завершится удаление. Получается параллельное, но не асинхронное

2022-05-14 08:42 UTC, r4start commented on internal/app/shortener.go
> +	if err := g.Wait(); err != nil {
> Мы же тут все равно ждем пока все удалится.

Мы здесь не ждём когда всё удалится. Только проверяем, что id корректные. Время ожидания линейно зависит от кол-ва переданных id в запросе.

У меня тут возник вопрос на который в задании не было ответа.
Что мы должны делать если один из id, переданных пользователем, некорректный?

В текущем варианте он получит ошибку сразу на запросе.

Можно эту часть кода переделать на отправку в канал этих данных и уже там декодировать и отправлять в dbstorage их на удаление.
Только надо решить, что мы будем делать в случае битых id. Либо всю пачку дропать, либо только битые.

2022-05-15 12:51 UTC, r4start commented on internal/app/shortener.go
> +	if err := g.Wait(); err != nil {
Сделал передачу id из запроса в канал.
В случае ошибки не удаляем ничего.

2022-05-16 09:48 UTC, lugingf approved these changes
Принято

2022-05-21 11:34 UTC, merged